### ISSUE TITLE
WSL: Command not found

### ISSUE THREAD

**Issue by Braunson** [luisaveiro/localhost-sonarqube#7]
#### Description

Setup following the README and trying to run `bash sonarqube` but I'm getting this error:

```
braunson@geekybeaver-PC:/mnt/c/Users/Braunson/Documents/GitHub/localhost-sonarqube/bin$ bash sonarqube
sonarqube: line 4: $'\r': command not found
sonarqube: line 6: $'\r': command not found
: No such file or directorysers/Braunson/Documents/GitHub/localhost-sonarqube/bin
sonarqube: line 9: $'\r': command not found
: No such file or directoryUsers/Braunson/Documents/GitHub/localhost-sonarqube/bin
sonarqube: line 12: $'\r': command not found
: No such file or directoryUsers/Braunson/Documents/GitHub/localhost-sonarqube/bin
sonarqube: line 15: $'\r': command not found
: No such file or directoryUsers/Braunson/Documents/GitHub/localhost-sonarqube/bin
sonarqube: line 18: $'\r': command not found
sonarqube: line 37: syntax error near unexpected token `$'{\r''
'onarqube: line 37: `function main() {
```

#### Expected Behaviour
Should start Sonarqube

#### Current Behaviour
Throws error instead

#### Steps to Reproduce

1. Using Windows 10 - WSL in Ubuntu
2. Copy down this repo
3. Run bash /your/path/sonarqube

* Localhost SonarQube version used: Latest (just cloned down)
* Operating System and version: Window 10 Home

**Comment by luisaveiro** [comment]
@Braunson I recommend you follow the solution provided in the Stack Exchange Network.
https://askubuntu.com/questions/966488/how-do-i-fix-r-command-not-found-errors-running-bash-scripts-in-wsl/969966#969966

Although the top solution recommends users to install `dos2unix` and requires you to convert the bash script using the command `dos2unix [file]`. Although this is a good solution, you will need to repeat this command for each shell script in this project. There are a total of 14 bash files in this project. The top solution will be time-consuming. This is why I suggested the second solution.

**Comment by Braunson** [comment]
Thanks @luisaveiro I've reinstalled within the WSL Ubuntu instance and outside the mounted Windows system.

I'm having issues however accessing the dashboard. This is the error when running `sonaqube dashboard`

> INFO: Opening SonarQube dashboard on http://localhost:9000
/home/braunson/localhost-sonarqube/bin/functions/console.sh: line 12: open: command not found
